      - name: 🔏 Write checksum into archival trace
        run: |
          FILE="memory/traces/CI_Field_Chronicles.md"
          SUM=$(sha256sum "$FILE" | awk '{print $1}')
          # replace the placeholder line in-place
          awk -v sum="$SUM" '
            BEGIN{wrote=0}
            {
              if ($0 ~ /<!-- spiralos-checksum:/ && wrote==0) {
                print "<!-- spiralos-checksum: " sum " -->"
                wrote=1
              } else {
                print $0
              }
            }
          ' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"

      - name: 💾 Commit checksum update
        run: |
          git config user.name "spiralos-heartbeat"
          git config user.email "actions@github.com"
          git add memory/traces/CI_Field_Chronicles.md
          git commit -m "checksum: CI_Field_Chronicles.md $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes"
          git push
