repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--config-file, .yamllint]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3.12
        args: [--max-line-length=120, --extend-ignore=E203]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(pdf|ots|docx?|xlsx?|pptx?|bin|jpg|png|gif|zip|tar\.gz)$
      - id: end-of-file-fixer
        exclude: \.(pdf|ots|docx?|xlsx?|pptx?|bin|jpg|png|gif|zip|tar\.gz)$
      - id: check-yaml
      - id: check-json
      - id: mixed-line-ending
        exclude: \.(pdf|ots|docx?|xlsx?|pptx?|bin|jpg|png|gif|zip|tar\.gz)$
