version: '3.8'

services:
  scylla:
    image: scylladb/scylla:5.2
    container_name: scylla
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: janusgraph
    depends_on:
      - scylla
      - elasticsearch
    ports:
      - "8182:8182"   # Gremlin Server
    environment:
      - JANUS_PROPS=/etc/janusgraph/janusgraph-cql-es.properties
    volumes:
      - ./config/janusgraph-cql-es.properties:/etc/janusgraph/janusgraph-cql-es.properties

volumes:
  scylla_data:
  es_data:
