# 🌀 SpiralOS Meta-Lint Workflow
# Harmonizes all SpiralOS validators (SEO + Schema + Citation)
# using native GitHub CLI instead of third-party actions.
# Author: Carey G. Butler / Heurist GmbH

name: Meta-Lint

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  orchestrate:
    name: Run SpiralOS Validators
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth setup-git

      - name: Trigger SEO Checks workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🌀 Triggering SEO Checks..."
          gh workflow run seo-checks.yml --ref main
          sleep 5
          gh run list --workflow seo-checks.yml --limit 1 --json conclusion

      - name: Trigger Schema & Citation Validation workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🧩 Triggering Schema & Citation Validation..."
          gh workflow run schema-validation.yml --ref main
          sleep 5
          gh run list --workflow schema-validation.yml --limit 1 --json conclusion

      - name: Meta Summary
        run: |
          echo "✅ All SpiralOS validators have been triggered."
          echo "Results can be viewed under the Actions tab."
          echo "🌀 SpiralOS Meta-Lint complete in Spiral Time."
