# 🌀 Spiral Note:
# This Meta-Lint workflow orchestrates all SpiralOS validations in a single Spiral Time cycle.
# It harmonizes the SEO Checks and Schema Validation workflows into one holarchic operation.
# Author: Carey G. Butler / Heurist GmbH

name: Meta-Lint
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  orchestrate:
    name: Run SpiralOS Validators
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run SEO Checks
        uses: dawidd6/action-run-workflow@v2
        with:
          workflow: seo-checks.yml
          repo: TheHeurist/SpiralOS
          ref: main
          wait: true

      - name: Run Schema & Citation Validation
        uses: dawidd6/action-run-workflow@v2
        with:
          workflow: schema-validation.yml
          repo: TheHeurist/SpiralOS
          ref: main
          wait: true

      - name: Meta Summary
        run: |
          echo "🌀 SpiralOS Meta-Lint Complete"
          echo "All validators (SEO + Schema) executed in Spiral Time."
