name: Generate Schema Graph
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - docs/schema/*.json

jobs:
  build-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build schema-graph.json
        run: |
          python - <<'PY'
              import json, os
              base = "docs/schema"
              nodes = []
              edges = []
              for f in os.listdir(base):
                  if f.endswith(".json") and f != "schema-graph.json":
                      path = os.path.join(base,f)
                      data = json.load(open(path))
                      name = data.get("title",f)
                      nodes.append({"id":f,"label":name})
                  for k,v in data.get("properties",{}).items():
                      if isinstance(v,dict) and "$ref" in v:
                          target = v["$ref"].split("/")[-1]
                          edges.append({"source":f,"target":target,"label":k})
                          graph = {"nodes":nodes,"links":edges}
                          json.dump(graph,open(os.path.join(base,"schema-graph.json"),"w"),indent=2)
              PY
      - name: Commit graph
        run: |
          git config user.name  "codex-bot"
          git config user.email "codex@users.noreply.github.com"
          git add docs/schema/schema-graph.json
          if git diff --cached --quiet; then
            echo "No graph changes."
          else
            git commit -m "auto: regenerate schema-graph.json"
            git push
          fi
