# 🧩 SpiralOS Schema & Citation Validation
# Validates JSON, YAML, and CITATION.cff; ensures Zenodo DOI reachability.
# Author: Carey G. Butler / Heurist GmbH

name: Schema & Citation Validation

on:
  push:
    branches: [ main, seo/** ]
  pull_request:
  workflow_dispatch:   # Allows manual or programmatic triggering

jobs:
  validate-jsonld:
    name: Validate JSON-LD and JSON syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Validate JSON and JSON-LD files
        run: |
          set -e
          find docs -type f \( -name "*.jsonld" -o -name "*.json" \) | while read f; do
            echo "Checking $f"
            jq empty "$f"
          done

  validate-yaml:
    name: Validate YAML schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint
      - name: Validate all YAML files
        run: |
          set -e
          yamllint -d "{extends: default, rules: {line-length: disable}}" docs/

  validate-citation:
    name: Validate CITATION.cff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate CITATION.cff
        uses: citation-file-format/cffconvert-github-action@main
        with:
          args: "--validate"

  validate-dois:
    name: Check DOI reachability
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check DOI reachability
        run: |
          set -e
          DOIS=$(grep -RhoE "zenodo\\.org/records/[0-9]{6,}" docs CITATION.cff | sort -u || true)
          for d in $DOIS; do
            echo "Checking https://$d"
            code=$(curl -s -o /dev/null -w "%{http_code}" "https://$d")
            if [ "$code" -lt 200 ] || [ "$code" -gt 399 ]; then
              echo "::warning title=DOI unreachable::$d returned $code"
            fi
          done
